# Generated by Django 5.1 on 2024-08-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to="media/"
            ),
        ),
    ]
